# Generated by Django 2.1 on 2018-08-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='appName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
