# Generated by Django 2.1 on 2018-09-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0002_config_appname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='new_posts_wait_time',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='oldest_author',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='oldest_permlink',
        ),
        migrations.RemoveField(
            model_name='scraper',
            name='post_batch_size',
        ),
        migrations.AddField(
            model_name='scraper',
            name='block_nbr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
