# Generated by Django 2.1 on 2018-09-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0004_question_answer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='carousel_slide_count',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='The number of questions to load in the home page carousel', null=True),
        ),
    ]
