# Generated by Django 2.1 on 2018-08-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('topic',)},
        ),
        migrations.AlterField(
            model_name='accesstoken',
            name='token',
            field=models.CharField(db_index=True, help_text='SHA-512 encrypted version of Steemconnect access token', max_length=160),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
    ]
