# Generated by Django 2.1 on 2018-08-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0002_auto_20180818_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='The main SteemQA application tag', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Scraper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodes', models.TextField(default='gtg.steem.house:8090,steemd.minnowsupportproject.org,steemd.privex.io,steemd.steemgigs.org,steemd.steemit.com,rpc.curiesteem.com,rpc.steemliberator.com,rpc.steemviz.com', help_text='The steem nodes to use (in order of priority)')),
                ('oldest_author', models.TextField(default='')),
                ('oldest_permlink', models.TextField(default='')),
            ],
        ),
    ]
