# Generated by Django 2.1 on 2018-08-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0003_config_scraper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='oldest_author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='oldest_permlink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
