# Generated by Django 2.1 on 2018-09-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0003_auto_20180902_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
