# Generated by Django 2.1 on 2018-09-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0005_config_carousel_slide_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='carousel_history',
            field=models.PositiveIntegerField(blank=True, default=7, help_text='Time period (in days) to report top questions in carousel', null=True),
        ),
    ]
