# Generated by Django 2.1 on 2018-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0006_auto_20180820_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='nodes',
            field=models.TextField(help_text='The steem nodes to use (in order of priority)'),
        ),
    ]
