# Generated by Django 2.1 on 2018-08-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0007_auto_20180820_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='nodes',
        ),
        migrations.AddField(
            model_name='scraper',
            name='steemd_nodes',
            field=models.TextField(default='gtg.steem.house:8090,steemd.minnowsupportproject.org,steemd.privex.io,steemd.steemgigs.org,steemd.steemit.com,rpc.curiesteem.com,rpc.steemliberator.com,rpc.steemviz.com', help_text='The steem nodes to use (in order of priority)'),
        ),
    ]
