# Generated by Django 2.1 on 2018-08-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steem', '0008_auto_20180820_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraper',
            old_name='steemd_nodes',
            new_name='nodes',
        ),
    ]
